//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OvertimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid EmployeeID { get; set; }
        public string NIK { get; set; }
        public string FullName { get; set; }
        public string Allowance { get; set; }
        public string DepartmentID { get; set; }
        public string PositionID { get; set; }
    }
}
