//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OvertimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Overtime
    {
        public System.Guid OvertimeID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.DateTime TimeStart { get; set; }
        public System.DateTime TimeFinish { get; set; }
        public double ActualHours { get; set; }
        public double CalculatedHours { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
